name: Node.js CI
on: ["push", "pull_request"]

jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - run: yarn install
    - uses: icrawl/action-eslint@v1
      with:
        custom-glob: "."